### ISSUE TITLE
在Ubuntu上运行时报错😣

### ISSUE THREAD

**Issue by xANoyU** [cxOrz/chaoxing-sign-cli#116]
已经yarn安装依赖并且yarn build过了

`ubuntu@VM-12-7-ubuntu:~/chaoxing-sign-cli$ yarn monitor
yarn run v1.22.19
$ node ./build/monitor.js
/home/ubuntu/chaoxing-sign-cli/build/monitor.js:80
    if (config?.monitor) {
               ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

运行yarn start时报错
`ubuntu@VM-12-7-ubuntu:~/chaoxing-sign-cli$ yarn start
yarn run v1.22.19
$ node ./build/index.js
/home/ubuntu/chaoxing-sign-cli/build/utils/helper.js:41
globalThis.JSON.parseJSON = parseJSON;
^

ReferenceError: globalThis is not defined
    at Object.<anonymous> (/home/ubuntu/chaoxing-sign-cli/build/utils/helper.js:41:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/chaoxing-sign-cli/build/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by xANoyU** [comment]
更新了下nodejs就好了qwq
