### ISSUE TITLE
登录账号时发生异常

### ISSUE THREAD

**Issue by AkagiYui** [cxOrz/chaoxing-sign-cli#193]
输入密码后发生异常：
```
chaoxing-sign-cli on  main is 📦 v4.3.5 via  v18.15.0 took 11s
❯ pnpm dev

> chaoxing-sign@4.3.5 dev D:\TempFiles\chaoxing-sign-cli
> turbo run dev:serve dev --filter=./apps/*

• Packages in scope: server, web
• Running dev:serve, dev in 2 packages
• Remote caching disabled
web:dev: cache bypass, force executing afd6ee980de3243e
server:dev:serve: cache bypass, force executing eae3be7328db44e9
web:dev:
web:dev: > web@2.7.0 dev D:\TempFiles\chaoxing-sign-cli\apps\web
web:dev: > vite --open
web:dev:
server:dev:serve:
server:dev:serve: > server@4.3.5 dev:serve D:\TempFiles\chaoxing-sign-cli\apps\server
server:dev:serve: > ts-node ./src/serve.ts
server:dev:serve:
web:dev:
web:dev:   VITE v3.2.5  ready in 454 ms
web:dev:
web:dev:   ➜  Local:   http://localhost:3000/
web:dev:   ➜  Network: use --host to expose
server:dev:serve: API Server: http://localhost:5000
server:dev:serve:
server:dev:serve:   TypeError: Cannot read properties of undefined (reading 'length')
server:dev:serve:       at userLogin (D:\TempFiles\chaoxing-sign-cli\apps\server\src\functions\user.ts:51:34)
server:dev:serve:       at processTicksAndRejections (node:internal/process/task_queues:95:5)
server:dev:serve:       at async D:\TempFiles\chaoxing-sign-cli\apps\server\src\serve.ts:27:18
server:dev:serve:       at async D:\TempFiles\chaoxing-sign-cli\apps\server\src\serve.ts:300:3
server:dev:serve:       at async bodyParser (D:\TempFiles\chaoxing-sign-cli\node_modules\.pnpm\koa-bodyparser@4.3.0\node_modules\koa-bodyparser\index.js:95:5)
server:dev:serve:
```

**Comment by cxOrz** [comment]
可能是ip异常，或者登陆操作异常。等一段时间，换个环境试一下
