### ISSUE TITLE
开启监听模式后，检测到签到信息就会报错，程序停止运行

### ISSUE THREAD

**Issue by zycn0910** [cxOrz/chaoxing-sign-cli#70]
return JSON.parse(hexToUtf8(hexStr));
              ^
SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseActivityHexJSON (D:\Desktop\科技改变一切\chaoxing-sign-cli\src\monitor.ts:59:15)
    at WebSocket.<anonymous> (D:\Desktop\科技改变一切\chaoxing-sign-cli\src\monitor.ts:218:33)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.emit (node:domain:475:12)
    at Receiver.receiverOnMessage (D:\Desktop\科技改变一切\chaoxing-sign-cli\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.emit (node:domain:475:12)
    at Receiver.dataMessage (D:\Desktop\科技改变一切\chaoxing-sign-cli\node_modules\ws\lib\receiver.js:528:14)
    at Receiver.getData (D:\Desktop\科技改变一切\chaoxing-sign-cli\node_modules\ws\lib\receiver.js:446:17)
PS D:\Desktop\科技改变一切\chaoxing-sign-cli>

**Comment by cxOrz** [comment]
是最新版本吗，加个q细说

**Comment by zycn0910** [comment]
是最新版本，我已在您的b站留言
